### ISSUE TITLE
Wrong link on softex.info

### ISSUE THREAD

**Issue by heikoklein** [softex-it/dictan-core#1]
Hi,
I'm not really sure if I'm writing at the correct place, but I wanted to create an fdl-database for dictan. The link on http://www.softex.info/index.php?option=com_content&view=article&id=51&Itemid=65 lead to a no longer existing google-code page. I guess this github repo is the successor for google-code? Eventually, you should update the softex.info link.
Best regards,
Heiko

**Comment by softex-it** [comment]
Hello, the link resolves fine to the format description. If you a looking for a way to create an fdl base, you could use the "Dictan Converter" from "Downloads" section of the same page. Underneath it's using dictan-core. Thank you!

**Comment by heikoklein** [comment]
It is the sentence from the mentioned page which doesn't work:
The Java library which allows to work with the FDB format is called Dictan-Core, and available at http://dictan-core.googlecode.com under the GNU LGPL v3 (and later) license.

**Comment by softex-it** [comment]
The link is fixed. Thanks for the note.
